### ISSUE TITLE
java.lang.NullPointerException error in VariantQC

### ISSUE THREAD

**Issue by ankita16lawarde** [BimberLab/DISCVRSeq#216]
[https://gatk.broadinstitute.org/hc/en-us/community/posts/12114421047195-java-lang-NullPointerException-error-in-VariantQC?page=1#community_comment_12301701379867](url)

I have uploaded a question in the above link. but the GATK support team asked me to contact you here as the problem is related to DISCVRSeq tool.

I look forward to hearing the probable reason behind the error, or any guidance on how to solve this problem would be very helpful.

Thank you,
Ankita

**Comment by bbimber** [comment]
The quick answer is that the tool is failing because there isnt a sequence dictionary, either within the VCF header or provided by your genome. I'll make the tool handle this situation with a more informative error, but I think the solution is either to make sure your FASTA file has a dictionary or include the sequence dictionary in the VCF header.

**Comment by bbimber** [comment]
Thanks for reporting this - it should be fixed in https://github.com/BimberLab/DISCVRSeq/releases/tag/1.3.24.

Note: it's possible the prior version would not have used the .dict file even if you provided it. This version should accept either a dictionary in the VCF or a standalone file from the genome.

**Comment by ankita16lawarde** [comment]
Hi,

Thank you for your reply. it was very helpful.
Although with the updated DISCVRSeq I still received the null error. But I used https://gatk.broadinstitute.org/hc/en-us/articles/360037425731-UpdateVCFSequenceDictionary
 this tool to change the contigs in the vcf file and variantQC could run successfully.

Thank you again for helping me.

**Comment by bbimber** [comment]
@ankita16lawarde Thanks for the feedback. Glad it worked, but i will try to find some time to test/fix the scenario where the VCF lacks a dictionary. 

Do you by chance have the actual stacktrace/error from the latest version? I wonder if there's a second place that needs an update.

**Comment by ankita16lawarde** [comment]
Hi BimberLab/DISCVRSeq,

Yes!
Please find the error message I got after using the new version of
DISCVRSeq tool.
I hope it helps

PFA.

Best Regards,
Ankita

**Comment by bbimber** [comment]
Hi @ankita16lawarde: were you intending to post an error message? Thanks.

**Comment by ankita16lawarde** [comment]
Hi BimberLab/DISCVRSeq,

I sent an email yesterday with the error file.

Do you want me to post it on the GitHub page?


Best Regards,
Ankita

**Comment by ankita16lawarde** [comment]
Hi,

Please check the error message i received after using the new version of DISCVRSeq.

Error page:
We are currently testing and validating Spark against non-Spark tools.

Reference Genomes location: /gpfs/hpc/databases/broadinstitute
Datasets info:
https://cloud.google.com/life-sciences/docs/resources/public-datasets/reference-genomes 
10:52:46.141 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/gpfs/space/home/etais/hpc_ankita.ee/Endometrial_cancer_Spain/DISCVRSeq-1.3.24.jar!/com/intel/gkl/native/libgkl_compression.so
10:52:46.287 INFO  VariantQC - ------------------------------------------------------------
10:52:46.290 INFO  VariantQC - DISCVR-seq Toolkit v1.3.24
10:52:46.291 INFO  VariantQC - For support and documentation go to https://software.broadinstitute.org/gatk/
10:52:46.291 INFO  VariantQC - Executing as hpc_ankita.ee@ares8 on Linux v3.10.0-1160.42.2.el7.x86_64 amd64
10:52:46.291 INFO  VariantQC - Java runtime: OpenJDK 64-Bit Server VM v1.8.0_265-b01
10:52:46.291 INFO  VariantQC - Start Date/Time: January 25, 2023 10:52:46 AM EET
10:52:46.291 INFO  VariantQC - ------------------------------------------------------------
10:52:46.291 INFO  VariantQC - ------------------------------------------------------------
10:52:46.291 INFO  VariantQC - HTSJDK Version: 3.0.1
10:52:46.291 INFO  VariantQC - Picard Version: unknown
10:52:46.291 INFO  VariantQC - Built for Spark Version: unknown
10:52:46.291 INFO  VariantQC - HTSJDK Defaults.COMPRESSION_LEVEL : 2
10:52:46.292 INFO  VariantQC - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
10:52:46.292 INFO  VariantQC - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
10:52:46.292 INFO  VariantQC - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
10:52:46.292 INFO  VariantQC - Deflater: IntelDeflater
10:52:46.292 INFO  VariantQC - Inflater: IntelInflater
10:52:46.292 INFO  VariantQC - GCS max retries/reopens: 20
10:52:46.292 INFO  VariantQC - Requester pays: disabled
10:52:46.292 INFO  VariantQC - Initializing engine
10:52:46.632 INFO  FeatureManager - Using codec VCFCodec to read file file:///gpfs/space/home/etais/hpc_ankita.ee/Endometrial_cancer_Spain/Files_VCF_GZ/BL_CHUS/BL_5_TSVC_variants_IonXpress_001.vcf
10:52:46.703 INFO  VariantQC - Done initializing engine
10:52:46.709 INFO  VariantQC - Total VariantEval instances: 8
10:52:46.881 INFO  Reflections - Reflections took 149 ms to scan 1 urls, producing 9 keys and 31 values 
10:52:46.990 INFO  Reflections - Reflections took 102 ms to scan 1 urls, producing 7 keys and 42 values 
10:52:46.997 INFO  VariantEvalEngine - Creating 3 combinatorial stratification states
10:52:47.001 INFO  VariantQC - Shutting down engine
[January 25, 2023 10:52:47 AM EET] com.github.discvrseq.walkers.variantqc.VariantQC done. Elapsed time: 0.02 minutes.
Runtime.totalMemory()=1248329728
***********************************************************************

UNEXPECTED ERROR: null

***********************************************************************
Please, search for this error in our issue tracker or post a new one:
java.lang.NullPointerException
	at java.util.Comparator.lambda$comparing$77a9974f$1(Comparator.java:469)
	at java.util.Collections$ReverseComparator2.compare(Collections.java:5232)
	at java.util.TimSort.binarySort(TimSort.java:296)
	at java.util.TimSort.sort(TimSort.java:239)
	at java.util.Arrays.sort(Arrays.java:1512)
	at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:353)
	at java.util.stream.Sink$ChainedReference.end(Sink.java:258)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:483)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at com.github.discvrseq.walkers.variantqc.Contig.getContigNames(Contig.java:49)
	at com.github.discvrseq.walkers.variantqc.Contig.<init>(Contig.java:26)
	at com.github.discvrseq.walkers.variantqc.ExtendedVariantEvalEngine.createVariantStratifier(ExtendedVariantEvalEngine.java:58)
	at org.broadinstitute.hellbender.tools.walkers.varianteval.VariantEvalEngine.initializeStratificationObjects(VariantEvalEngine.java:812)
	at org.broadinstitute.hellbender.tools.walkers.varianteval.VariantEvalEngine.validateAndInitialize(VariantEvalEngine.java:215)
	at com.github.discvrseq.walkers.variantqc.ExtendedVariantEvalEngine.doValidateAndInitialize(ExtendedVariantEvalEngine.java:37)
	at com.github.discvrseq.walkers.variantqc.ExtendedVariantEvalEngine.<init>(ExtendedVariantEvalEngine.java:28)
	at com.github.discvrseq.walkers.variantqc.VariantQC$VariantEvalWrapper.configureEngine(VariantQC.java:570)
	at com.github.discvrseq.walkers.variantqc.VariantQC.onTraversalStart(VariantQC.java:380)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1093)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:140)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
	at com.github.discvrseq.Main.main(Main.java:50)

**Comment by bbimber** [comment]
@ankita16lawarde Thanks for posting the error. Can you please try with version 1.3.26? I dont know if this will fix it, but it includes expanded validation over the dictionary and perhaps better reporting on exactly what is failing.
